### PR TITLE
See #4, perfect address format

### PR DESCRIPTION
**Pull request by zhiwenxuan**
The address is ` ` when the `streetNumber` and `streetName` are both empty but expecting it to be an empty string

```js
result.address = result.streetNumber + ' ' + result.streetName
```

### CODE REVIEW

**Comment by zhiwenxuan** [comment]
Is this project still maintained？ @ajoslin

**Comment by ajoslin** [comment]
Good addition :+1:

Didn't see your initial PR. I updated the PR to use my preferred syntax for this. Can you add a unit test? if you don't have time LMK and I'll add one and publish.

**Comment by ajoslin** [comment]
Merged via bf18c66a874ad21c401ca57587739b58492f2592 and added tests. Thank you @zhiwenxuan.

**Comment by ajoslin** [comment]
Published `1.3.0`

**Pull request merged**
